
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydb
      username: 'root'
      password: '1234'
      authentication-database: admin

spring.webflux.hiddenmethod.filter.enabled: true
spring.devtools.restart.exclude: static/**, public/**

logging.level.web: DEBUG
